Select Ceil(8.29) As Ceil_Value From Dual; 
Select Ceil(-3.9) As Ceil_Negative From Dual;
Select Ceil(17/3) As Ceil_Division From Dual;
Select Floor(9.76) As Floor_Value From Dual;
Select Floor(-5.3) As Floor_Negative From Dual;
Select Floor(15/4) As Floor_Division From Dual;
Select Sqrt(625) As Square_Root From Dual;
Select Sqrt(2) As Square_Root_2 From Dual;
Select Abs(8.29) As Absolute_Value From Dual;
Select Abs(-3.14) As Absolute_Negative From Dual;
Select Abs(-42) As Absolute_Column_Value From Dual;
Select Sysdate As Now From Dual;
Select To_Char(Sysdate, 'DD-MON-YYYY HH24:MI:SS') As Date_Time_Format From Dual;
Select Systimestamp As System_Timestamp From Dual;
Select Least('Apple', 'Banana', 'Cherry') As Least_String From Dual;
Select Greatest('Apple', 'Banana', 'Cherry') As Greatest_String From Dual;
Select Ltrim('    Trim me') As Leading_Spaces_Removed From Dual;
Select Rtrim('I love India                ') As Trailing_Spaces_Removed From Dual;
SELECT RPAD('Anjaly', 15, 'X') AS Right_Padded_Name FROM DUAL;
Select Rpad(To_Char(123), 6, '0') As Right_Padded_Number From Dual;
Select Reverse_String('uoyevol I') As Reversed From Dual;
SELECT  CASE WHEN 'racecar' = reverse ('racecar') THEN 'Palindrome'
ELSE 'Not Palindrome' END AS Result From Dual;
Select Length('Oracle Database') As String_Length From Dual;
Select 'Oracle'||' '||'SQL'||' '||'is'||' '||'powerful'||' '||'and'||' '||'flexible' From Dual;
Select Concat('Anjaly','S') As Full_Name From Dual;
Select Substr('India is my country',Instr('India is my country','is'),2) As Substring_Is From Dual;
Select Substr('Anjaly', 3, 3) As Middle_Three_Chars From Dual;
Select Substr('Substring', 1, 3) As First_Three_Chars From Dual;